layout: sidebar
style: dark #light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
    # sort_by options:
    # - pushed
    # - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - kmanas/SQL-for-Data-Science

social_media:
  #kaggle: #your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: kmanas
  # instagram: your_username
  # keybase: your_username
  linkedin: #your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: makke_n
  # unsplash: your_username
  ## vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  kaggle: kaihatsusha

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
  
  - name: SQL
    web_url: https://github.com/topics/sql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sql/sql.png
  
  - name: Jupyter Notebook
    web_url: https://github.com/topics/jupyter-notebook
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/jupyter-notebook/jupyter-notebook.png
  
  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/flask/flask.png
    
  - name: Data visualization
    web_url: https://github.com/topics/data-visualization
    image_url: #https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/tensorflow/tensorflow.png

  - name: Machine learning
    web_url: https://github.com/topics/machine-learning
    image_url:
